<MOI38> <ERROR> <ERROR_NUMBER Value="0000" /> <ERROR_TEXT />
<ERROR_SUB Value="0000" /> <RETURN_IND Value="000" /> </ERROR> <INQUIRY_INFO>
<TRANSACTION_TIME Value="2013-07-15-16.04.38.418828" /> <DISPLAY_TRANS_TIME
	Value="1604" /> <TRANSACTION_CODE Value="L" /> <TRANSACTION_DATE
	Value="20130715" /> <NUMBER_GROUP Value="10000" /> </INQUIRY_INFO> <UPDATE_INFO>
<STATUS Value="R" /> <NUMBER_TYPE Value="8" /> </UPDATE_INFO> <PROTECTED_FIELDS>
<PROT_NUMBER_TYPE_IND /> <PROT_STATUS_IND /> <PROT_INTERCEPT_IND /> <PROT_DISC_USOC_IND />
<PROT_RCY_IND /> </PROTECTED_FIELDS> </MOI38>